# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: cebuhomepages
description: "Cebu Home Page, helping you buy and sell your property with ease."
author:
  name: Luchelle
  email: luchelle@cebuhomepages.com

# Grunt handles images and assets.
#exclude: ['images', 'css', 'js', 'fonts',
#         '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

include: ['.htaccess']

# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
#   auto_ids: true
#   footnote_nr: 1
#   entity_output: as_char
#   toc_levels: 1..6
#   use_coderay: false
#   coderay:
#     coderay_wrap: div
#     coderay_line_numbers: inline
#     coderay_line_numbers_start: 1
#     coderay_tab_width: 4
#     coderay_bold_every: 10
#     coderay_css: style

highlighter: pygments

#baseurl: ""
#cdn: ""


#baseurl: "http://localhost:3000"
#cdn: "http://localhost:3000"
#img_host: "http://localhost:3000"
#baseurl: "https://cebuhomepages.github.io"
#cdn: "https://googledrive.com/host/0B3imkbmUgHpnflNkYjhIcElFVm9WVm51VHQ1NEdIb2QwWWcyRFNDSDRUbHViNmdPUDV1Tjg"
#baseurl: "https://www.cebuhomepages.com"
#baseurl: "http://www.cebuhomepages.com.s3-website-ap-southeast-1.amazonaws.com"
#img_host: "https://dl.dropboxusercontent.com/u/39191093"

#img_host: "https://dmcagfio3mnht.cloudfront.net"
#cdn: "https://dmcagfio3mnht.cloudfront.net"
#img_host: "https://googledrive.com/host/0B3imkbmUgHpnflNkYjhIcElFVm9WVm51VHQ1NEdIb2QwWWcyRFNDSDRUbHViNmdPUDV1Tjg"
#cdn: "https://dl.dropboxusercontent.com/u/39191093"

#### Local DEV
#baseurl: "http://localhost:3000"
cdn: "http://127.0.0.1:4000"
img_host: "http://127.0.0.1:4000"

#### Live
#baseurl: "https://www.cebuhomepages.com"
#img_host: "https://dmcagfio3mnht.cloudfront.net"
#cdn: "https://dmcagfio3mnht.cloudfront.net"


enforce_ssl: "cebuhomepages.com"

title: Cebu Home Pages

owner:
  fullname: Luchelle Ann Cabigon
  nickname: Luchelle
  nickname_short: Luch
  job: Licensed Real Estate Broker
  service: I'm helping you Buy or Sell your property
  address: "Hernan Cortes Street, Casuntingan, Mandaue City, CEBU,PH"
  phone: "+639176312463"
  phone_display: "0917 631 2463"
  email: luchelle@cebuhomepages.com
  site: www.cebuhomepages.com
  whatsapp:
    username: +639176312463

fbc-comments-firebase: https://chpcomments.firebaseio.com/

logo: /images/logo.jpg
profile_pic: /images/person-360x360.jpg

name: Cebu Home Pages
copyright_date: 2015

# Social Setup
facebook: https://facebook.com/cebuhomepages
messenger: //m.me/cebuhomepages
xfb:
  app_id: 270751863008126
  on: true
  og_image: /images/logo.jpg # Default image for Open Graph tag
  og_image_type: image/jpg
  og_image_width: 300
  og_image_height: 300
  conversion:
    readers:
      id: 6030369792953
      value: 0.01
  wca: 
    pixel_id: 729985667100309

twitter: https://twitter.com/cebuhomepages
google_plus: https://google.com/+Cebuhomepages

google_analytics: UA-48709253-1
xgoogle:
  page_id: 116568573527527678461
  google-site-verification: vYBf-jDAw2Ewu5a3SqpYhUjPxer2j46QUK7ohpBFFXU


root:
  css: /canvas/css
  js: /canvas/js
  images: /canvas/images
  r: /canvas
  r4x1: /v4.1
